# 1) Build 단계: Node.js로 번들링
FROM node:18-alpine AS builder
WORKDIR /app

# 빌드 시 주입
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ARG REACT_APP_KAKAO_MAP_API
ENV REACT_APP_KAKAO_MAP_API=${REACT_APP_KAKAO_MAP_API}
ARG REACT_APP_AUTH_DOMAIN
ENV REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
ARG REACT_APP_PROJECT_ID
ENV REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
ARG REACT_APP_STORAGE_BUCKET
ENV REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET}
ARG REACT_APP_MESSAGIN_ID
ENV REACT_APP_MESSAGIN_ID=${REACT_APP_MESSAGIN_ID}
ARG REACT_APP_APP_ID
ENV REACT_APP_APP_ID=${REACT_APP_APP_ID}
ARG REACT_APP_MEASUREMENT_ID
ENV REACT_APP_MEASUREMENT_ID=${REACT_APP_MEASUREMENT_ID}
ARG REACT_APP_GOOGLE_ANALYSTIC
ENV REACT_APP_GOOGLE_ANALYSTIC=${REACT_APP_GOOGLE_ANALYSTIC}
ARG REACT_APP_KAKAO_MAP_API
ENV REACT_APP_KAKAO_MAP_API=${REACT_APP_KAKAO_MAP_API}

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# 2) Production 단계: Nginx로 정적 파일 서빙
FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html

ENV NODE_ENV=production

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
